name: ssh deploy
  # You may pin to the exact commit or the version.
  # uses: easingthemes/ssh-deploy@191986574c0735ffad7ae1a297a414d6e6f95375

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
         node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: PUSH TO SERVER
        uses: easingthemes/ssh-deploy@v2.1.5
        with:        
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # Remote user
          REMOTE_USER: ubuntu
          # Remote port
          SOURCE: ""
          # Arguments to pass to rsync
          TARGET: "dev-reactjs"
          # ARGS: |

